### PR TITLE
Functions

### PR DESCRIPTION
**Pull request by Mr-Oregano**
Add:
 - Function declarations
 - Function calls
 - Runtime library with built-in functions

### CODE REVIEW

**Comment by ethanlchristensen** [comment]
erm

**Comment by ethanlchristensen** [comment]
image
Thoughts on this @Mr-Oregano ?

**Comment by Mr-Oregano** [comment]
> image Thoughts on this @Mr-Oregano ?

Erm ethan... did you forget this wasn't on main branch again?

**Comment by Mr-Oregano** [comment]
You did bring a little bug with the interactive shell to my attention tho

**Comment by ethanlchristensen** [comment]
@Mr-Oregano I thought I had built the functions branch but for some reason it was main! aplogies!

**Pull request merged**
